n_threads: 20
cpu: false
gpu_id: 0
local_rank: -1
resize_radio: 1.0
r_resize: 10
device_id: "0"
sam2_pretrain: "/mnt/40B2A1DBB2A1D5A6/lyx/project/MODEL/Sam2/sam2_hiera_large.pt"
adadim: 32
rfbdim: 128
dataset_name: "FMOST"
dataset_img_path: "/mnt/40B2A1DBB2A1D5A6/lyx/TMP/neuron_tracing_from4090_1/Reference/DeepBranchTracer-new/DeepBranchTracer-main/data/YiFu0729/dataset/training_datasets/"
dataset_img_test_path: "/mnt/40B2A1DBB2A1D5A6/lyx/TMP/neuron_tracing_from4090_1/Reference/DeepBranchTracer-new/DeepBranchTracer-main/data/YiFu0729/dataset/test_datasets/"
test_data_path: "/mnt/40B2A1DBB2A1D5A6/lyx/TMP/neuron_tracing_from4090_1/Reference/DeepBranchTracer-new/DeepBranchTracer-main/data/YiFu0729/test/images/"
predict_seed_path: "/mnt/40B2A1DBB2A1D5A6/lyx/TMP/neuron_tracing_from4090_1/Reference/DeepBranchTracer-new/DeepBranchTracer-main/data/Results/Neuron_3d/Predicts/seed/"
predict_centerline_path: "/mnt/40B2A1DBB2A1D5A6/lyx/TMP/neuron_tracing_from4090_1/Reference/DeepBranchTracer-new/DeepBranchTracer-main/data/Results/Neuron_3d/Predicts/pre_centerline_test/"
predict_swc_path: "/mnt/40B2A1DBB2A1D5A6/lyx/TMP/neuron_tracing_from4090_1/Reference/DeepBranchTracer-new/DeepBranchTracer-main/data/Results/Neuron_3d/Predicts/pre_swc_test/"
batch_size: 8
valid_rate: 0.1
data_shape: [64, 64, 64]
test_patch_height: 64
test_patch_width: 64
test_patch_depth: 64
stride_height: 48
stride_width: 48
stride_depth: 48
model_save_dir: "/mnt/40B2A1DBB2A1D5A6/lyx/TMP/neuron_tracing_from4090_1/Reference/DeepBranchTracer-new/DeepBranchTracer-main/data/Results/Neuron_3d/model/model_"
log_save_dir: "/mnt/40B2A1DBB2A1D5A6/lyx/TMP/neuron_tracing_from4090_1/Reference/DeepBranchTracer-new/DeepBranchTracer-main/data/Results/Neuron_3d/log/log_"
epochs: 30
lr: 0.0003
vector_bins: 50
train_seg: true
print_info: false
tracing_strategy_mode: "anglecenterline"
train_or_test: "inference_segmentation"
to_restore: false
